### ISSUE TITLE
Unable to Start GreenNav

### ISSUE THREAD

**Issue by gastonche** [nav-e/nav-e#25]
HI have have setup upmy development environment for greennav as specified in the documentaion on the wiki, but when i run npm start on the greenav front end  and go to the browser to http://localhost:3000 , i get a connection error, indicating that the app has not served on port 3000,this is the output on my console when i run 

> npm start

`> GreenNav@0.1.2 start C:\Users\Gaston\opensource\greenNav\GreenNav
> react-scripts start`

I need help so as to get started soon

**Comment by tom3012** [comment]
Hi @gastonche,

we need a little bit more information, because on my machine it starts automatically in my default browser. Which Browser do you use? Which OS? Have you waited long enough, because there should appear "Starting development server..."  in your terminal. Port 3000 should should not be blocked or used by another service!

Regards
