### ISSUE TITLE
Show error messages

### ISSUE THREAD

**Issue by maxlorenz** [nav-e/nav-e#57]
Add support for messages/notifications
Show error messages when requests fail

**Comment by abhishek71994** [comment]
Could you give a little bit more info about the issue?

**Comment by abhishek71994** [comment]
Hey @maxlorenz .. any update?

**Comment by maxlorenz** [comment]
Sure @abhishek71994 ! I'd like to have a small React message box to display custom backend errors, timeouts etc.

**Comment by abhishek71994** [comment]
What are the errors and timeouts to begin with? Do  you want a modal to pop up?

**Comment by abhishek71994** [comment]
Do they include xhr requests in Menu.js? Also I've changed some file names from GreenNav to Nave "Nav-e" did not look to be working. Check it out in the new PR that I'll make once I get this issue fixed

**Comment by abhishek71994** [comment]
@maxlorenz updates?

**Comment by maxlorenz** [comment]
Sure! Yes, any xhr request can fail or return error messages which are ignored right now. The server can send [plain error messages](https://github.com/nav-e/routing/blob/3ae93cc0a752dce707be0681485e2ccc568efed4/server/server.go#L42) when something goes wrong but this should be updated to send json, I think

**Comment by shreyakupadhyay** [comment]
Changing [response.json()](https://github.com/nav-e/nav-e/blob/master/src/GreenNav.js#L127) to response.text() because whenever there is "Error: could not find path" server response, this throws an error and which is matched by [.catch()](https://github.com/nav-e/nav-e/blob/master/src/GreenNav.js#L146) . Using try and catch instead of using if else helps in handling response errors dynamically and no need to add cases for different error responses. Also, adding this.xhr.onerror to handle errors with the xhr request.

**Comment by abhishek71994** [comment]
So @shreyakupadhyay I was working on it. But seems like you already have a solution?

**Comment by shreyakupadhyay** [comment]
Yes, I have a solution and have submitted a PR to resolve the issue.

**Comment by abhishek71994** [comment]
@maxlorenz looks like this issue is solved? Also @shreyakupadhyay can you check your gitter once? I have pinged you there.
